# fly.toml app configuration file generated for lotto-numbers on 2023-12-16T14:09:59+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lotto-numbers"
primary_region = "syd"

[build]
image = "ghcr.io/danstis/lotto-numbers:latest"

[env]
ENVIRONMENT = "production"
PORT = "8080"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 256
