version: "3.4"

services:
  app:
    build:
      context: ../
      dockerfile: deploy/dockerfile
    image: ghcr.io/danstis/lotto-numbers:latest
    environment:
      PORT: "8080"
      TZ: Australia/Brisbane
    restart: always
    ports:
      - 8092:8080
