FROM golang:1.26-alpine AS builder

# hadolint ignore=DL3018
RUN apk add --no-cache git

ARG BUILD=0.0.0-development
ARG PORT=8080

WORKDIR /github.com/danstis/lotto-numbers/
COPY ./go.mod .
COPY ./go.sum .
RUN go mod download
COPY . .
RUN mkdir /app && \
    GOOS=linux go build -ldflags "-s -w -X 'github.com/danstis/lotto-numbers/internal/version.Version=$BUILD'" -o /app/lotto-numbers ./cmd/lotto-numbers

FROM alpine:3
# hadolint ignore=DL3018
RUN apk --no-cache add ca-certificates
WORKDIR /app
COPY --from=builder /app/* ./
COPY --from=builder /usr/local/go/lib/time/zoneinfo.zip /
ENV ENVIRONMENT="development" \
	PORT="$PORT" \
	UPTRACE_DSN="" \
	TZ=Australia/Brisbane \
	ZONEINFO=/zoneinfo.zip
CMD [ "./lotto-numbers" ]
EXPOSE $PORT
